### PR TITLE
Move realtime directory from inasafe/realtime-develop and add InaSAFE 3.5.4 as a submodule

### PR DESCRIPTION
**Pull request by myarjunar**

### CODE REVIEW

**Comment by Gustry** [comment]
It looks good @myarjunar !

I think you should use inasafe 3.5 in the submodule. For now I saw it's using develop as of Dec 16, 2016. Is-it fine @lucernae ?

**Comment by Gustry** [comment]
Can you make a PR to remove the realtime folder from inasafe ? @myarjunar

**Comment by ismailsunni** [comment]
@Gustry I think he use version 3.5.4 or 9f19af7

LGTM @myarjunar

**Comment by Gustry** [comment]
Ok sorry, it's 16 December, but on the master branch ;-)

**Pull request merged**
